Making the lib work with rxjava 1.2.1+ and updated play services
Mauin/servant pull request #13
Opened 2017-02-27 14:43 UTC by CDehning

2017-02-28 08:14 UTC, Mauin requested changes

2017-02-28 08:14 UTC, Mauin commented on servant/src/main/java/com/mtramin/servant/GoogleApiClientObservable.java
>          return Observable.fromEmitter(new GoogleApiClientObservable(context, googleApi),
As `Observable.fromEmitter(Action1, BackpressureMode)` has been deprecated with RxJava v1.2.7 this should use `Observable.create(Action1, BackpressureMode)` instead. (Just change `fromEmitter` to `create` and that should work)

2017-02-28 12:07 UTC, CDehning commented on servant/src/main/java/com/mtramin/servant/GoogleApiClientObservable.java
>          return Observable.fromEmitter(new GoogleApiClientObservable(context, googleApi),
Done

2017-02-28 12:14 UTC, Mauin approved these changes

2017-02-28 12:14 UTC, Mauin commented on servant/src/main/java/com/mtramin/servant/GoogleApiClientObservable.java
>          return Observable.fromEmitter(new GoogleApiClientObservable(context, googleApi),
Awesome, thanks! Will wait for CI to go green and will look at building a new release later this week.

2017-02-28 12:26 UTC, merged

2017-03-02 17:52 UTC, Rainer-Lang commented
@Mauin Is it possible to get a new release?

2017-03-02 18:49 UTC, Mauin commented
@Rainer-Lang I'm pushing the new releases right now.

2017-03-02 21:33 UTC, Rainer-Lang commented
Thanks